### ISSUE TITLE
Support use persist in lens object.

### ISSUE THREAD

**Issue by NiuGuohui** [dhmk083/dhmk-zustand-lens#12]
Sometimes, we may need partial state persistence.

**Comment by dhmk083** [comment]
There is built-in persist middleware.

You may want to use [partialize option](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#partialize) for that.

**Comment by jhensley** [comment]
I'd actually argue that it's not built into `partialize` ... specifically partialize hits the storage method on any change to the store, not just those that made it through the partialize filter. 

See https://github.com/pmndrs/zustand/issues/902

**Comment by dhmk083** [comment]
Yeah, but there is a good suggestion of how it could be fixed: [https://github.com/pmndrs/zustand/issues/902#issuecomment-1094415011](https://github.com/pmndrs/zustand/issues/902#issuecomment-1094415011).

Also, you can use debounced storage save function.

**Comment by roddc** [comment]
In order to use persist in lens object, I changed these two functions:
```
const _set = (partial, replace, ...args) =>
    set(
      parentValue => {
        const ourOldValue: any = getIn(parentValue || {}, normPath);
        const ourTmpValue = typeof partial === 'function' ? partial(ourOldValue) : partial;
        const isPlain = isPlainObject(ourOldValue);
        const ourNextValue = replace || !isPlain ? ourTmpValue : { ...ourOldValue, ...ourTmpValue };

        const isSame = isPlain ? shallowEqual(ourOldValue as any, ourNextValue) : ourOldValue === ourNextValue; // todo Object.is
        return isSame ? parentValue : setIn(parentValue || {}, normPath, ourNextValue);
      },
      false,
      ...args,
    );

  const _get = () => getIn(get() || {}, normPath);
```
Because the `setIn` and `getIn` will throw error if the first paramter is undefined or null, we just need to ensure we pass non-null value to these two functions

**Comment by dhmk083** [comment]
I'm not quite familiar with persist middleware, how could store state be undefined or null? I mean, shouldn't initial state be used in that case? Could you provide an example please?

**Comment by roddc** [comment]
> I'm not quite familiar with persist middleware, how could store state be undefined or null? I mean, shouldn't initial state be used in that case? Could you provide an example please?

I will try to explain what I understand from the source code of zustand.
The [state ](https://github.com/pmndrs/zustand/blob/main/src/vanilla.ts#L63)is set to undefined initially when `createStore` is called. The `persist` middleware will call [get](https://github.com/pmndrs/zustand/blob/main/src/middleware/persist.ts#L319) on creation if `skipHydration` is set to false; therefore, the `persist` will not create the storage in the first place when using it inside a lens object.

Also, I hope there is a standalone `api` object for every substore so they will have an own `persist` object.

**Comment by dhmk083** [comment]
Sorry for the delay. I think you may be using lens object the wrong way. Lens description in readme file may be misleading, I think I need to edit it. Lens doesn't create an actual sub-`store`, rather it is a subpart of one store, so it shares `api` object with its parent store. It's just like a lens concept from functional programming.

[Here's an example](https://codesandbox.io/s/quizzical-ellis-fdz6q9?file=/src/index.ts) of how to use it with `persist` middleware. Note, that you have to specify a custom `merge` function, which performs a deep merge. This package has such function and I also plan to add a shortcut function with swapped order of arguments to simplify `merge: (a: any, b) => mergeDeep(b, a)` into `merge: mergeDeepLeft`.
