### ISSUE TITLE
Unable to resolve peer dependency 'zustand@"^4.0.0"'

### ISSUE THREAD

**Issue by Lykan9999** [dhmk083/dhmk-zustand-lens#14]
### Context
Working on a React web app initialized with Vite, Trying out Zustand state management library. Needed a way to structure app state in a nested fashion 
```
// for example
State
├ Authentication: AuthenticationSTate
├ UserSettings: UserSettingsState
├ RecentVisits: RecentVisitsState
├ etc...
```
After research this library seemed to be the solution for such an implementation, however when I tried installing it I kept getting the following error 
```
npm WARN Could not resolve dependency:
npm WARN peer zustand@"^4.0.0" from @dhmk/zustand-lens@2.0.4
```
I am currently using `zustand@4.0.0-rc.1` tried looking for a non-rc 4.0.0. version but with no luck.

After going through the code on [zustand-4 branch "package.json"](/dhmk083/dhmk-zustand-lens/tree/zustand-4/package.json#L29) it looks like the version given for zustand doesn't exist.

**Comment by dhmk083** [comment]
Yeah, I thought `^4.0.0` condition would also include beta versions, but seems it's not true. But it's only a warning, not an error, so the package should be installed anyway, just ignore the warning.
