### ISSUE TITLE
possibility to call another slice action from inside a lens

### ISSUE THREAD

**Issue by pinkynrg** [dhmk083/dhmk-zustand-lens#19]
From a slice X,Y,Z I need to call an action of a slice COMMON that has a shared method among all other slices.

I used to call it this way:

```
get().COMMON.setToast({ toast: UPDATE_ROWS_CATEGORY_SUCCESS })
```

once I wrap the slice with the lens() method get() only returns the type of the lensed slice i'm working on. Is it possibile to let get() access the whole store?

**Comment by dhmk083** [comment]
The whole store is passed to a `lens()` function as the third argument, same as in zustand. To type it provide a second type argument to a `lens()` function or a `Lens<>` type.

```ts
const mySlice = lens<SliceState, StoreState>((set, get, store) => {...})
```

**Comment by dhmk083** [comment]
Yes, this is correct.
