### ISSUE TITLE
Typescript example has typescript error `Type ... is missing the following properties from StoreApi`

### ISSUE THREAD

**Issue by b-novikov-ipersonality** [dhmk083/dhmk-zustand-lens#6]
Hey. 

[Codesandbox](https://codesandbox.io/s/red-http-jj8kbx?file=/src/mystore.ts)

I tried following typescript example but ran into error. I then tried to recreate the code from example but it does show an error, too. 

I provided codesandbox where example typescript code is in file `fromexample.ts` and my store is in file `mystore.ts`

After providing the store missing properties `getState`, `setState`, `subscribe` and `destroy` (which I shouldn't do) it now shows an error 
```javascript
Type 'StoreApi<Store>' is missing the following properties from type 'Store': id, name, nestedts
``` 
but these properties are definitely defined.  

I don't understand how to type the store properly. Can you please provide direction?

**Comment by dhmk083** [comment]
I also faced this error. That's because zustand upgraded to v4 and it's seems to be incompatible with the old middleware typings.
I will update types later. Right now you can stay on zustand version 3.*.

**Comment by b-novikov-ipersonality** [comment]
@dhmk083 alright, thank you. 

May you answer a question on how to use `zustand-lens` please? I want to know what is the proper way to use it. 

Say I have a `headerStore` and I want to access it
```javascript
// header store
const headerStore = lens<HeaderState>((set, get) => { ... })
// then I merge it into global store
type Store = {
  header: typeof headerStore
  // other store types
}
const stateCreator: StateCreator<Store> = (set, get) => ({
  header: headerStore,
  // other stores
})
const useStore = create(withLenses(stateCreator));
```

How do I do that? From `useStore`? Directly from `headerStore`?

**Comment by dhmk083** [comment]
You can use it the same way you use zustand. 

```ts
type HeaderStore {
  open: boolean
  setOpen(open: boolean)
}

const headerStore = (set) => ({
  open: false,
  setOpen: (open?: boolean) =>
    set((state) => ({ open: open || !state.open }))
})
```

In a React component:

```ts
const MyComponent = () => {
  const {open, setOpen} = useStore(s => s.header) // HeaderStore

  return <div>
    {open && <p>Header is opened</p>}
    <button onClick={() => setOpen(!open)}>Toggle</button>
  </div>
}
```

Via zustand's getState:

```ts
const header = useStore.getState().header // HeaderStore
header.setOpen(true)
```

Access it from your store:

```ts
const useStore = create(withLenses((_, get) => ({
  header: lens(headerStore),

  // some store method
  doSmthWithHeader() {
    // note, this `get` function gives access to the whole store 
    const header = get().header // HeaderStore
    header.setOpen(!header.open)

    // also note, that `header` variable here now refers to the old state,
    // you need to re-read it again, to get fresh state.

    const header2 = get().header
  }
})))
```

If your header sub-store needs data from global store, you can pass a function to a `headerStore`. Imagine, that your store has another `config` sub-store and you can open a header only if it's not disabled:

```ts
const headerStore = (disableOpen: () => boolean) => (set) => ({
  open: false,
  setOpen: (open?: boolean) =>
    set((state) => ({ open: !disableOpen() && (open || !state.open) }))
})

const useStore = create(withLenses((_, get) => ({
  header: lens(headerStore(() => get().config.disableOpen)),

  config: lens(set => ({
    disableOpen: false,
    setDisableOpen: (disable) => set({disableOpen: disable})
  })), 

  // some store method
  doSmthWithHeader() {
    // note, this `get` function gives access to the whole store 
    const header = get().header // HeaderStore
    header.setOpen(!header.open)

    // also note, that `header` variable here now refers to the old state,
    // you need to re-read it again, to get fresh state.

    const header2 = get().header
  }
})))
```

**Comment by dhmk083** [comment]
I've updated typings for zustand v4. You can install them via `npm install @dhmk/zustand-lens@next`. Once v4 becomes stable, I will update main branch.
