### ISSUE TITLE
Using with `devtools` middleware

### ISSUE THREAD

**Issue by 2Pacalypse-** [dhmk083/dhmk-zustand-lens#7]
Hi, I love your project as it allows me to do exactly what I need without too much type boilerplate. However, I have one question when using your library together with the `devtools` middleware.

`devtools` middleware extends the setter function, so you can supply the name of the action as a third argument to `set`. But I can't seem to make that work together with this library. Do you have any ideas on how to do that? Thank you!

Example code:
```ts
interface UsersSlice {
  byName: Map<string, User>
  listUsers: () => void
}

const usersSlice: Lens<UsersSlice> = (set) => ({
  byName: new Map(),

  async listUsers() {
    const data = await listUsersFromServer()
    const byName = new Map(data.users.map((user) => [user.name, user]))

    set({ byName }, false, '@users/listUsers')
  },
})

export const useStore = create(
  devtools(
    immer(
      withLenses(() => ({
        users: lens(usersSlice),
      }))
    ),
    { serialize: true }
  )
)
```

**Comment by dhmk083** [comment]
I've updated the package. Now it should work.

However, it's not strongly typed. Instead, setter function now accepts any trailing arguments. This way it's more universal and will work with any other middlewares which add extra arguments.

I wish I could type it better, like core zustand package does, but right now I don't know how to do it properly.

**Comment by 2Pacalypse-** [comment]
Thx!

And don't worry about it, this is good enough for now. Typing zustand middlewares seems ridiculously hard.

Initially, I actually had a custom middleware which would change the signature of the `set` method (inside devtools middleware) from:
```js
set(partial, replace, actionName)
```
to
```js
set(partial, actionName, replace)
```
since `replace` param was useless to me and just added boilerplate. But typing that seemed impossible...

**Comment by dhmk083** [comment]
Yeah, I saw typings for v4 middleware. They are mind-blowing.

About `replace` param. I thought about adding optional map function parameter to `lens` function. Something like that:

```js
const stateSlice = lens(
  set => ({
    ...
    action() {
      set({...}, 'action-name')
    }
  }), 
  parentSet => (partial, actionName, replace) => parentSet(partial, replace, actionName)
)

// can even create a helper
// and it can be easily typed
const namedLens = fn => lens(fn, namedSetter)
```

It would allow more flexibility, but I'm not sure if it's really useful.

**Comment by 2Pacalypse-** [comment]
Yeah, that might actually be useful. Since in zustand, each middleware can change the signature of the `set` method any way they like, it would be nice to have an easy way to type that.

**Comment by dhmk083** [comment]
By the way, now you can type `set` like this:

```ts
interface Slice {
  id: number;
  test();
}

type NamedSet<T> = (
  partial: Partial<T> | ((state: T) => Partial<T> | void),
  replace?: boolean | undefined,
  name?: string
) => void;

lens<Slice, any, NamedSet<Slice>>((set) => ({
  id: 1,

  test() {
    set({ id: 2 }, false, 'action-name');
  },
}));

// another way

type NamedLens<T extends object, S extends object = any> = Lens<T, S, NamedSet<T>>

const slice: NamedLens<Slice> = (set) => ({
  id: 1,

  test() {
    set({id: 2}, false, 'action-name')
  }
})
```

I will also add that map parameter later.

**Comment by dhmk083** [comment]
It turned out, that it's hard to type additional map parameter. Instead, it's easier to wrap creator function into a middleware function. I've added some helpers for zustand 4. Here is an example:

```ts
import { lens, namedSetter } from "@dhmk/zustand-lens";

const test = lens(
  namedSetter((set) => ({
    name: "abc",

    setName() {
      set({ name: "def" }, "@test/setName");
    },
  }))
);
```
