### ISSUE TITLE
Expose the global state in the lenses

### ISSUE THREAD

**Issue by 2Pacalypse-** [dhmk083/dhmk-zustand-lens#8]
It would be nice if it were possible to access global state in the lenses. I.e., change the `lens` signature from:
```ts
lens(fn: (set, get) => T): T
```
to
```ts
lens(fn: (set, get, getRoot) => T): T
```
or something like that.

**Comment by dhmk083** [comment]
Sure. But do you want a state getter only or a full api object from zustand? One which has `getState`, `setState` and `subscribe` functions. It could be more useful.

**Comment by dhmk083** [comment]
Or maybe `withLenses2` approach isn't great. Because if your state slices reside in separate files, it won't work. It's only useful if slices are defined in place.

**Comment by dhmk083** [comment]
Done. Now lens takes the third parameter `api` which is the same as in zustand's `create` function.

You can type it like this:

```ts
interface TodosSlice {
  todos: string[]
}

interface State {
  user: string
  todosSlice: TodosSlice
}

const store = create<State>(withLenses(() => ({
  user: 'me',

  todosSlice: lens<TodosSlice, State>((set, get, api) => ({
    todos: ['write code'],

    test() {
      const user = api.getState().user // string
    }
  }))
})))
```

**Comment by 2Pacalypse-** [comment]
That's awesome!

Yeah, initially I was thinking of just accessing the root store, but having the whole `api` object seems much more useful.
