### ISSUE TITLE
how much work would it take to extend this library to support lenses over arrays

### ISSUE THREAD

**Issue by lukesmurray** [dhmk083/dhmk-zustand-lens#9]
At the moment lenses only work for plain objects. I would love to extend this library to support arrays as well.

**Comment by dhmk083** [comment]
Could you provide a use case? 

Also, you should be able to achieve array support with `createLens` function, although, as noted in your your PR, it has a problem with types. I will fix that.

**Comment by lukesmurray** [comment]
See my comment here https://github.com/dhmk083/dhmk-zustand-lens/pull/10#issuecomment-1137143358.

In summary, I don't think there is a strong use case and I ended up taking an alternative approach.
